# Generated by Django 4.2.16 on 2025-03-11 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='一级菜单')),
            ],
            options={
                'verbose_name_plural': '一级菜单表',
            },
        ),
        migrations.CreateModel(
            name='PermGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='权限组名')),
                ('menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.menu', unique=True, verbose_name='所属菜单')),
            ],
            options={
                'verbose_name_plural': '权限组',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='权限名称')),
                ('url', models.CharField(max_length=32, unique=True, verbose_name='URL')),
                ('perm_code', models.CharField(max_length=32, verbose_name='权限代码')),
                ('perm_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.permgroup', verbose_name='所属权限')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='角色名')),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.permission', verbose_name='拥有的权限')),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('nickname', models.CharField(max_length=30, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254)),
                ('roles', models.ManyToManyField(to='rbac.role')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
